//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GammaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocProduction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocProduction()
        {
            this.DocProductionProducts = new HashSet<DocProductionProducts>();
            this.DocWithdrawal = new HashSet<DocWithdrawal>();
        }
    
        public System.Guid DocID { get; set; }
        public Nullable<System.Guid> ProductionTaskID { get; set; }
        public Nullable<int> InPlaceID { get; set; }
        public Nullable<bool> HasWarnings { get; set; }
        public Nullable<System.Guid> DocOrderId { get; set; }
    
        public virtual Docs Docs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocProductionProducts> DocProductionProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocWithdrawal> DocWithdrawal { get; set; }
        public virtual ProductionTasks ProductionTasks { get; set; }
        public virtual Places Places { get; set; }
    }
}
