//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GammaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docs
    {
        public System.Guid DocID { get; set; }
        public Nullable<bool> IsMarked { get; set; }
        public Nullable<int> DocTypeID { get; set; }
        public string Number { get; set; }
        public bool IsConfirmed { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string PrintName { get; set; }
        public Nullable<int> PlaceID { get; set; }
        public Nullable<byte> ShiftID { get; set; }
        public System.DateTime Date { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> IsFromOldGamma { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<byte> BranchID { get; set; }
        public Nullable<System.Guid> PersonGuid { get; set; }
    
        public virtual DocProduction DocProduction { get; set; }
        public virtual DocWithdrawal DocWithdrawal { get; set; }
        public virtual Places Places { get; set; }
    }
}
