//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GammaService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GammaEntities : DbContext
    {
        public GammaEntities()
            : base("name=GammaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActiveProductionTasks> ActiveProductionTasks { get; set; }
        public virtual DbSet<Reports> Reports { get; set; }
        public virtual DbSet<Templates> Templates { get; set; }
        public virtual DbSet<ModbusDevices> ModbusDevices { get; set; }
        public virtual DbSet<CurrentPlaceUsers> CurrentPlaceUsers { get; set; }
        public virtual DbSet<DocProduction> DocProduction { get; set; }
        public virtual DbSet<DocProductionProducts> DocProductionProducts { get; set; }
        public virtual DbSet<Docs> Docs { get; set; }
        public virtual DbSet<DocWithdrawal> DocWithdrawal { get; set; }
        public virtual DbSet<DocWithdrawalProducts> DocWithdrawalProducts { get; set; }
        public virtual DbSet<ProductItems> ProductItems { get; set; }
        public virtual DbSet<ProductPallets> ProductPallets { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductionTasks> ProductionTasks { get; set; }
        public virtual DbSet<C1CMeasureUnits> C1CMeasureUnits { get; set; }
        public virtual DbSet<C1CCharacteristics> C1CCharacteristics { get; set; }
        public virtual DbSet<Places> Places { get; set; }
        public virtual DbSet<RemotePrinters> RemotePrinters { get; set; }
        public virtual DbSet<PlaceRemotePrinters> PlaceRemotePrinters { get; set; }
        public virtual DbSet<PlaceRemotePrinterSettings> PlaceRemotePrinterSettings { get; set; }
        public virtual DbSet<RemotePrinterLabels> RemotePrinterLabels { get; set; }
        public virtual DbSet<LocalSettings> LocalSettings { get; set; }
        public virtual DbSet<ProductionTaskConverting> ProductionTaskConverting { get; set; }
    
        public virtual ObjectResult<Nullable<System.Guid>> GetActiveSourceSpools(Nullable<int> placeID)
        {
            var placeIDParameter = placeID.HasValue ?
                new ObjectParameter("PlaceID", placeID) :
                new ObjectParameter("PlaceID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("GetActiveSourceSpools", placeIDParameter);
        }
    }
}
