//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GammaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceRemotePrinters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlaceRemotePrinters()
        {
            this.PlaceRemotePrinterSettings = new HashSet<PlaceRemotePrinterSettings>();
        }
    
        public int PlaceID { get; set; }
        public int ModbusDeviceID { get; set; }
        public int RemotePrinterID { get; set; }
        public int PlaceRemotePrinterID { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<bool> IsDefaultPrinterForGamma { get; set; }
    
        public virtual ModbusDevices ModbusDevices { get; set; }
        public virtual Places Places { get; set; }
        public virtual RemotePrinters RemotePrinters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaceRemotePrinterSettings> PlaceRemotePrinterSettings { get; set; }
    }
}
